services:
  tracker:
    build: .
    image: droplet-tracker
    volumes:
      - "${INPUT_DIR}:/app/input"     # входные видео будут доступны в /app/input
      - "${OUTPUT_DIR}:/app/output"   # результаты сохранятся в /app/output
    working_dir: /app
  dev:
    build: .
    entrypoint: []
    image: droplet-tracker-dev
    volumes:
      - ./app:/src                     # код для редактирования
      - "${INPUT_DIR}:/app/input"      # те же видео
      - "${OUTPUT_DIR}:/app/output"    # и выходные папки
    working_dir: /src
    command: sleep infinity            # держит контейнер живым
    stdin_open: true
    tty: true